branches:
  only:
  - pelican
language: python
python:
- 3.5
install:
- pip install -r requirements.txt
script:
- make publish
notifications:
  email:
    on_success: never
    on_failure: never
env:
  global:

before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh